server:
  port: 8081
#  servlet:
#    context-path: /order

spring:
  application:
    name: order-api
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

management:
  endpoints:
    web:
      exposure:
        include: "*"
