server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: order
          uri: http://localhost:8081/order
          predicates:
            - Path=/order/**
          filters:
            - StripPrefix=1  # 转发过滤前缀个数
        - id: user
          uri: http://localhost:8082/user
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1  # 转发过滤前缀个数
      enabled: true
      loadbalancer:
        use404: true
#  main:
#    allow-bean-definition-overriding: true

logging:
  level:
    org.springframework:cloud.gateway: debug